name: caronapp
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.3
  path_provider: ^2.0.0
  mobx: ^2.0.0
  flutter_mobx: ^2.0.0
  provider: ^5.0.0
  intl: ^0.18.1
  enum_to_string: ^2.0.1
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  firebase_auth: ^4.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.0
  build_runner: ^2.0.0

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/fonts/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
